import type { FC } from 'react'
import {
  Activity,
  BarChart3,
  BookOpen,
  Box,
  Brain,
  Briefcase,
  Building2,
  CandlestickChart,
  ChartCandlestick,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  ClipboardList,
  Clock,
  Coins,
  Crosshair,
  Database,
  DollarSign,
  Eye,
  FileBarChart,
  FileText,
  Fingerprint,
  GanttChartSquare,
  Globe,
  Grid3X3,
  HandCoins,
  Home,
  Layers,
  LayoutDashboard,
  LineChart,
  List,
  ListChecks,
  Map,
  Megaphone,
  Menu,
  MessagesSquare,
  Monitor,
  Newspaper,
  PanelLeftClose,
  PanelLeftOpen,
  PieChart,
  Pin,
  Podcast,
  Radar,
  Scale,
  ScanLine,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Sigma,
  SlidersHorizontal,
  Star,
  Stars,
  Table,
  Target,
  Telescope,
  Ticket,
  TrendingDown,
  TrendingUp,
  User,
  Users,
  Wallpaper,
  Watch,
  Waypoints,
  Zap,
} from 'lucide-react'

export const iconMap: Record<string, FC<{ className?: string; size?: number }>> = {
  Activity,
  BarChart3,
  BookOpen,
  Box,
  Brain,
  Briefcase,
  Building2,
  CandlestickChart,
  ChartCandlestick,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  ClipboardList,
  Clock,
  Coins,
  Crosshair,
  Database,
  DollarSign,
  Eye,
  FileBarChart,
  FileText,
  Fingerprint,
  GanttChartSquare,
  Globe,
  Grid3X3,
  HandCoins,
  Home,
  Layers,
  LayoutDashboard,
  LineChart,
  List,
  ListChecks,
  Map,
  Megaphone,
  Menu,
  MessagesSquare,
  Monitor,
  Newspaper,
  PanelLeftClose,
  PanelLeftOpen,
  PieChart,
  Pin,
  Podcast,
  Radar,
  Scale,
  ScanLine,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Sigma,
  SlidersHorizontal,
  Star,
  Stars,
  Table,
  Target,
  Telescope,
  Ticket,
  TrendingDown,
  TrendingUp,
  User,
  Users,
  Wallpaper,
  Watch,
  Waypoints,
  Zap,
}

export const ICON_LIST = [
  { value: 'Home', label: '首頁' },
  { value: 'LayoutDashboard', label: '儀表板' },
  { value: 'BarChart3', label: '長條圖' },
  { value: 'LineChart', label: '折線圖' },
  { value: 'ChartLine', label: '線圖' },
  { value: 'ChartCandlestick', label: 'K線' },
  { value: 'CandlestickChart', label: 'K線圖' },
  { value: 'ChartColumn', label: '柱狀圖' },
  { value: 'ChartPie', label: '圓餅圖' },
  { value: 'PieChart', label: '餅圖' },
  { value: 'TrendingUp', label: '上漲' },
  { value: 'TrendingDown', label: '下跌' },
  { value: 'Activity', label: '活動' },
  { value: 'Zap', label: '閃電' },
  { value: 'Target', label: '目標' },
  { value: 'Crosshair', label: '瞄準' },
  { value: 'CircleDollarSign', label: '金錢' },
  { value: 'Coins', label: '金幣' },
  { value: 'DollarSign', label: '美元' },
  { value: 'HandCoins', label: '交易' },
  { value: 'ShoppingCart', label: '購物車' },
  { value: 'Briefcase', label: '公事包' },
  { value: 'Building2', label: '建築' },
  { value: 'Globe', label: '全球' },
  { value: 'Database', label: '資料庫' },
  { value: 'Sigma', label: '統計' },
  { value: 'SlidersHorizontal', label: '設定滑桿' },
  { value: 'Settings', label: '設定' },
  { value: 'Users', label: '用戶' },
  { value: 'User', label: '個人' },
  { value: 'Shield', label: '安全' },
  { value: 'Search', label: '搜尋' },
  { value: 'Eye', label: '查看' },
  { value: 'BookOpen', label: '書本' },
  { value: 'FileText', label: '文件' },
  { value: 'FileBarChart', label: '報表' },
  { value: 'ScrollText', label: '卷軸' },
  { value: 'ClipboardList', label: '清單' },
  { value: 'ListChecks', label: '核對' },
  { value: 'List', label: '列表' },
  { value: 'Table', label: '表格' },
  { value: 'Grid3X3', label: '網格' },
  { value: 'Layers', label: '圖層' },
  { value: 'Box', label: '盒子' },
  { value: 'Map', label: '地圖' },
  { value: 'Radar', label: '雷達' },
  { value: 'Waypoints', label: '路徑' },
  { value: 'GanttChartSquare', label: '甘特圖' },
  { value: 'ScanLine', label: '掃描' },
  { value: 'Fingerprint', label: '指紋' },
  { value: 'Brain', label: '智能' },
  { value: 'Stars', label: '星級' },
  { value: 'Pin', label: '圖釘' },
  { value: 'Clock', label: '時鐘' },
  { value: 'Watch', label: '手錶' },
  { value: 'Telescope', label: '望遠鏡' },
  { value: 'Megaphone', label: '公告' },
  { value: 'Newspaper', label: '新聞' },
  { value: 'Monitor', label: '螢幕' },
  { value: 'Wallpaper', label: '壁紙' },
  { value: 'MessagesSquare', label: '訊息' },
  { value: 'Menu', label: '選單' },
  { value: 'Ticket', label: '票券' },
  { value: 'Scale', label: '天平' },
  { value: 'Podcast', label: '廣播' },
]

export function getIconComponent(
  iconName: string | null | undefined,
): FC<{ className?: string; size?: number }> | null {
  if (!iconName) return null
  return iconMap[iconName] || null
}
